const TEXT_POOL = [
      "今日份快乐", "周末散步", "天晴有风", "你在身边", "生活是礼物", "路过好风景", "记录这一刻", "小确幸",
      "心情放映中", "刚刚好的一天", "把日子拍成诗", "此刻很喜欢", "平凡但闪亮", "慢慢来比较快", "今天也很可爱", "正在发光",
      "Good Day", "Hello Weekend", "Love This Moment", "Stay Golden", "Sweet Memory", "Happy Vibes",
      "今日份快乐 😊", "晴天收集计划 ☀️", "碎片日常 📸", "刚好遇见你 💙", "一起去看海 🌊", "散步小分队 🚶",
      "奶呼呼的一天 🧋", "快乐加载中 ✨", "普通但珍贵 🤍", "咔嚓一下 📷", "有你真好 🫶", "出发去浪漫 🎈",
      "周末治愈局 🍃", "今晚看月亮 🌙", "好天气营业中 🌤️", "打卡成功 ✅", "可爱超标 🐾", "这张超喜欢 😍",
      "今天也要开心鸭", "小日子慢慢过", "心动进行时", "把温柔存档", "收藏今天的光", "日常加载完毕",
      "等风也等你", "海边吹吹风", "山野有回响", "回忆有温度", "给生活比个耶", "一起吃好吃的",
      "假期模式开启", "旅行进行中", "在人间撒欢", "把烦恼按暂停", "这天值得纪念", "镜头里的我们",
      "笑容请签收 😄", "今天超顺利 🍀", "晚霞收集者 🌇", "心情是彩色的 🌈", "冰可乐和夏天 🧊",
      "出门即快乐 🚗", "和你一起真好 💫", "吃饱饱就幸福 🍜", "春天请回答 🌸", "冬天要抱抱 ❄️",
      "被风亲了一下 🍃", "元气满格 ⚡", "快乐不打烊 🪩", "见面就是礼物 🎁", "下一站是惊喜 🎠",
      "今天份的糖分", "拍拍拍停不下", "你是镜头焦点", "银河掉进眼睛里", "愿望正在靠近",
      "平平无奇小天才", "把快乐翻倍", "再忙也要开心", "生活需要暂停键", "小美好进行中",
      "时光轻轻落笔", "心事写在云里", "值得反复回味", "把爱留在照片里", "镜头懂我",
      "松弛感拉满", "浪漫在线营业", "热爱不降温", "把烦恼调成静音", "日子闪闪发亮",
      "此处应有掌声", "请查收今日可爱", "风景和你都很甜", "人间值得打卡", "等一个好天气",
      "Let's make memories", "Sunshine on repeat", "Caught in a good moment", "Smile, it's today",
      "Little joys, big heart", "Made of soft days", "Weekend state: ON", "Good things incoming",
      "Just us and the sky", "Frame full of love", "Stay cozy stay happy", "Mood: golden hour",
      "A tiny lovely life", "Keep the sparkle", "Made for this moment", "Cloud nine energy",
      "One day, one memory", "Soft light, soft heart", "Chill and cherish", "Life in snapshots",
      "Happiness looks good", "Hello, beautiful now", "Best day ever?", "Savor the little things",
      "Slow days, warm hearts", "Sun-kissed and blessed", "Dreaming in daylight", "Memories in motion",
      "好事会发生", "万物皆可期待", "今天是好日子", "微笑是最好的滤镜", "故事未完待续",
      "世界在发光", "把好运拍下来", "认真生活的人最可爱", "被幸福包围", "眼里有星星",
      "风吹哪页读哪页", "今天请温柔一点", "热爱漫无边际", "慢慢也很厉害", "请保持热爱",
      "平安喜乐", "日常小浪漫", "你来人间一趟很值得", "不赶路去感受路", "从容是最好的状态",
      "记录一万次开心", "把时间浪费在美好上", "心动在每一帧", "自由在风里", "把喜欢装进相册",
      "今天份可爱到账", "出片进行时", "咔嚓是快乐开关", "拍照即治愈", "这一秒很珍贵",
      "猫猫式松弛 🐱", "狗狗式开心 🐶", "奶茶续命成功 🧋", "今天有花花 🌼", "去看海啦 🌊",
      "晚风很温柔 🍃", "抬头就是好运 ☁️", "阳光正好 ☀️", "月亮也在偷笑 🌙", "星星替我说晚安 ✨",
      "请你吃糖呀 🍬", "一起发呆吧 🫧", "拥抱今天 🤍", "把烦恼丢给风 🪁", "好心情已签收 ✅"
      , "今日关键词：开心", "把小事过成诗", "平淡日子也发光", "快乐请续杯", "按下幸福快门",
      "有趣正在发生", "这一天很有分量", "把温柔揉进风里", "落日和我都很温柔", "今天就到这儿吧",
      "喜欢是藏不住的", "热爱生活的证据", "把路走成风景", "日常也值得庆祝", "写给今天的明信片",
      "慢慢走，深深爱", "被时间偏爱的瞬间", "和光同尘", "越简单越快乐", "平凡里的高光",
      "把故事拍成电影", "小情绪有出口", "所有遇见都刚好", "在生活里种花", "快乐都有回音",
      "阳光打了个招呼", "今天也是可爱的你", "世界比想象温柔", "把美好装进口袋", "有风有你有自由",
      "所有答案都在路上", "做自己的太阳", "不要忘记抬头", "看见生活的小确幸", "让心情晒晒太阳",
      "Nothing but good vibes", "Tiny moment, huge joy", "Proof of a lovely day", "Keep calm and glow",
      "Better days are here", "Lucky to be here", "Happiness in pixels", "Captured and cherished",
      "Light, laugh, love", "Hold this feeling", "This is the good part", "Soft and sunny mood",
      "Memory lane unlocked", "Let the moment linger", "Everything feels right", "Bloom where you are",
      "Home is this moment", "Breathing in joy", "Collecting little wonders", "Pause and smile",
      "Wander and wonder", "Golden light diary", "A postcard from now", "Simple days, rich heart",
      "All smiles today", "Small wins count", "Stay present stay bright", "Love this tiny life",
      "今天要有好消息 📩", "把可爱打包带走 🎀", "好运正在派件 🚚", "浪漫存档成功 💾", "轻轻松松过一天 🛋️",
      "今天喝了快乐水 🥤", "把烦恼吹散 🌬️", "心动报警 💘", "这帧我很喜欢 🖼️", "世界请对我好一点 🌎",
      "快门一响好运登场 📸", "能量补充中 🔋", "在路上也在发光 🛣️", "温柔有形状 ☁️", "把日落装回家 🌇",
      "想你时天都变甜 🍓", "和快乐撞个满怀 🤗", "今日份心安 🍵", "好天气请保持 🌤️", "小幸运连连看 🍀",
      "啊这也太好看了 😍", "元气开机成功 🟢", "今天主打一个松弛 🧘", "快乐请不要排队 🪄", "明天继续发光 ✨"
    ];
